# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: dunovank@gmail.com
author_name: Kyle Dunovan
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: theme
labextension_name: jupyterlab_darkside_theme
mimetype: ''
mimetype_name: ''
project_short_description: A dark theme for JupyterLab.
python_name: jupyterlab_darkside_theme
repository: 'https://github.com/dunovank/jupyterlab_darkside_theme'
test: true
viewer_name: ''

